#CONSUMO10
SSymbolC1 <- "GRUMAB.MX"
ETFC1 <- "CONSUMO.MX"
PARTICIPACIONC1 <- "11.87"

SSymbolC2 <- "BIMBOA.MX"
ETFC2 <- "CONSUMO.MX"
PARTICIPACIONC2 <- "12.10"

SSymbolC3 <- "KOF"
ETFC3 <- "CONSUMO.MX"
PARTICIPACIONC3 <- "12.03"

SSymbolC4 <- "BACHOCOB.MX"
ETFC4 <- "CONSUMO.MX"
PARTICIPACIONC4 <- "3.64"

SSymbolC5 <- "SORIANAB.MX"
ETFC5 <- "CONSUMO.MX"
PARTICIPACIONC5 <- "2.81"

SSymbolC6 <- "WALMEX.MX"
ETFC6 <- "CONSUMO.MX"
PARTICIPACIONC6 <- "12.13"

SSymbolC7 <- "KIMBERA.MX"
ETFC7 <- "CONSUMO.MX"
PARTICIPACIONC7 <- "12.00"

SSymbolC8 <- "LALAB.MX"
ETFC8 <- "CONSUMO.MX"
PARTICIPACIONC8 <- "4.81"

#ARCA CONTINENTAL
SSymbolC9 <- "AC.MX" 
ETFC9 <- "CONSUMO.MX"
PARTICIPACIONC9 <- "11.41"

SSymbolC10 <- "FEMSAUB.MX"
ETFC10 <- "CONSUMO.MX"
PARTICIPACIONC10 <- "11.91"

#CHNTRAC
SSymbolCH1 <- "JD"
ETFCH1 <- "CHNTRAC.MX"
PARTICIPACIONCH1 <- "10.92"

SSymbolCH2 <- "CTRP"
ETFCH2 <- "CHNTRAC.MX"
PARTICIPACIONCH2 <- "9.94"

SSymbolCH3 <- "EDU"
ETFCH3 <- "CHNTRAC.MX"
PARTICIPACIONCH3 <- "9.06"

SSymbolCH4 <- "CHL"
ETFCH4 <- "CHNTRAC.MX"
PARTICIPACIONCH4 <- "10.23"

SSymbolCH5 <- "BIDU"
ETFCH5 <- "CHNTRAC.MX"
PARTICIPACIONCH5 <- "10.19"

SSymbolCH6 <- "BABA"
ETFCH6 <- "CHNTRAC.MX"
PARTICIPACIONCH6 <- "9.57"

SSymbolCH7 <- "NTES"
ETFCH7 <- "CHNTRAC.MX"
PARTICIPACIONCH7 <- "9.05"

SSymbolCH8 <- "CEO"
ETFCH8 <- "CHNTRAC.MX"
PARTICIPACIONCH8 <- "5.78"

SSymbolCH9 <- "SNP"
ETFCH9 <- "CHNTRAC.MX"
PARTICIPACIONCH9 <- "3.55"

SSymbolCH10 <- "VIPS"
ETFCH10 <- "CHNTRAC.MX"
PARTICIPACIONCH10 <- "9.01"

#BRTRAC
SSymbolB1 <- "ABEV"
ETFB1 <- "BRTRAC.MX"
PARTICIPACIONB1 <- "15.46"

SSymbolB2 <- "VALE"
ETFB2 <- "BRTRAC.MX"
PARTICIPACIONB2 <- "13.31"

SSymbolB3 <- "PBR"
ETFB3 <- "BRTRAC.MX"
PARTICIPACIONB3 <- "12.26"

SSymbolB4 <- "ITUB"
ETFB4 <- "BRTRAC.MX"
PARTICIPACIONB4 <- "9.96"

SSymbolB5 <- "BBD"
ETFB5 <- "BRTRAC.MX"
PARTICIPACIONB5 <- "9.47"

SSymbolB6 <- "ERJ"
ETFB6 <- "BRTRAC.MX"
PARTICIPACIONB6 <- "8.40"

SSymbolB7 <- "VIV"
ETFB7 <- "BRTRAC.MX"
PARTICIPACIONB7 <- "8.05"

SSymbolB8 <- "BRFS"
ETFB8 <- "BRTRAC.MX"
PARTICIPACIONB8 <- "6.53"

SSymbolB9 <- "GGB"
ETFB9 <- "BRTRAC.MX"
PARTICIPACIONB9 <- "6.33"

SSymbolB10 <- "SID"
ETFB10 <- "BRTRAC.MX"
PARTICIPACIONB10 <- "4.83"

#ENLACE10
SSymbolE1 <- "AMXA.MX"
ETFE1 <- "ENLACE.MX"
PARTICIPACIONE1 <- "12.49"

SSymbolE2 <- "OMAB.MX"
ETFE2 <- "ENLACE.MX"
PARTICIPACIONE2 <- "10.98"

SSymbolE3 <- "PINFRA.MX"
ETFE3 <- "ENLACE.MX"
PARTICIPACIONE3 <- "11.23"

SSymbolE4 <- "GAPB.MX"
ETFE4 <- "ENLACE.MX"
PARTICIPACIONE4 <- "11.33"

SSymbolE5 <- "VOLARA.MX"
ETFE5 <- "ENLACE.MX"
PARTICIPACIONE5 <- "11.90"

SSymbolE6 <- "ASURB.MX"
ETFE6 <- "ENLACE.MX"
PARTICIPACIONE6 <- "11.66"

SSymbolE7 <- "ICA.MX"
ETFE7 <- "ENLACE.MX"
PARTICIPACIONE7 <- "1.00"

SSymbolE8 <- "OHLMEX.MX"
ETFE8 <- "ENLACE.MX"
PARTICIPACIONE8 <- "10.37"

SSymbolE9 <- "AEROMEX.MX"
ETFE9 <- "ENLACE.MX"
PARTICIPACIONE9 <- "7.24"

SSymbolE10 <- "IDEALB-1.MX"
ETFE10 <- "ENLACE.MX"
PARTICIPACIONE10 <- "10.89"


SSymbolQ1 <- "AAPL"
ETFQ1 <- "QQQ"
PARTICIPACIONQ1 <- "10.82"

SSymbolQ2 <- "MSFT"
ETFQ2 <- "QQQ"
PARTICIPACIONQ2 <- "8.41"

SSymbolQ3 <- "AMZN"
ETFQ3 <- "QQQ"
PARTICIPACIONQ3 <- "6.51"

SSymbolQ4 <- "FB"
ETFQ4 <- "QQQ"
PARTICIPACIONQ4 <- "4.97"

SSymbolQ5 <- "GOOG"
ETFQ5 <- "QQQ"
PARTICIPACIONQ5 <- "4.79"

SSymbolQ6 <- "GOOGL"
ETFQ6 <- "QQQ"
PARTICIPACIONQ6 <- "4.21"

SSymbolQ7 <- "INTC"
ETFQ7 <- "QQQ"
PARTICIPACIONQ7 <- "2.98"

SSymbolQ8 <- "CMCSA"
ETFQ8 <- "QQQ"
PARTICIPACIONQ8 <- "2.88"

SSymbolQ9 <- "CSCO"
ETFQ9 <- "QQQ"
PARTICIPACIONQ9 <- "2.61"

SSymbolQ10 <- "AMGN"
ETFQ10 <- "QQQ"
PARTICIPACIONQ10 <- "2.01"

SSymbolEA1 <- "ALSEA.MX"
ETFEA1 <- "ALSEA.MX"
PARTICIPACIONEA1 <- "100"



vector.Ssymbol <- c(SSymbolC1, SSymbolC2, SSymbolC3, SSymbolC4, SSymbolC5, SSymbolC6, SSymbolC7,SSymbolCH1,SSymbolCH2, SSymbolCH3, SSymbolCH4, SSymbolCH5, SSymbolCH6, SSymbolCH7, SSymbolCH8, SSymbolCH9, SSymbolCH10, SSymbolB1, SSymbolB2, SSymbolB3, SSymbolB4, SSymbolB5, SSymbolB6, SSymbolB7, SSymbolB8, SSymbolB9, SSymbolB10,SSymbolEA1,SSymbolE1,SSymbolE2,SSymbolE3,SSymbolE4,SSymbolE5,SSymbolE6,SSymbolE7,SSymbolE8,SSymbolE9,SSymbolE10,SSymbolQ1,SSymbolQ2,SSymbolQ3,SSymbolQ4,SSymbolQ5,SSymbolQ6,SSymbolQ7,SSymbolQ8,SSymbolQ9,SSymbolQ10 )
vector.etf <- c(ETFC1, ETFC2, ETFC3, ETFC4, ETFC5, ETFC6, ETFC7, ETFCH1, ETFCH2, ETFCH3, ETFCH4, ETFCH5, ETFCH6, ETFCH7, ETFCH8, ETFCH9, ETFCH10, ETFB1, ETFB2, ETFB3, ETFB4, ETFB5, ETFB6, ETFB7, ETFB8, ETFB9, ETFB10,ETFEA1,ETFE1,ETFE2,ETFE3,ETFE4,ETFE5,ETFE6,ETFE7,ETFE8,ETFE9,ETFE10,ETFQ1,ETFQ2,ETFQ3,ETFQ4,ETFQ5,ETFQ6,ETFQ7,ETFQ8,ETFQ9,ETFQ10 )
vector.participacion <- c(PARTICIPACIONC1, PARTICIPACIONC2, PARTICIPACIONC3, PARTICIPACIONC4, PARTICIPACIONC5,PARTICIPACIONC6, PARTICIPACIONC7, PARTICIPACIONCH1, PARTICIPACIONCH2, PARTICIPACIONCH3, PARTICIPACIONCH4, PARTICIPACIONCH5, PARTICIPACIONCH6, PARTICIPACIONCH7, PARTICIPACIONCH8, PARTICIPACIONCH9, PARTICIPACIONCH10, PARTICIPACIONB1, PARTICIPACIONB2, PARTICIPACIONB3, PARTICIPACIONB4, PARTICIPACIONB5, PARTICIPACIONB6, PARTICIPACIONB7, PARTICIPACIONB8, PARTICIPACIONB9, PARTICIPACIONB10,PARTICIPACIONEA1,PARTICIPACIONE1,PARTICIPACIONE2,PARTICIPACIONE3,PARTICIPACIONE4,PARTICIPACIONE5,PARTICIPACIONE6,PARTICIPACIONE7,PARTICIPACIONE8,PARTICIPACIONE9,PARTICIPACIONE10,PARTICIPACIONQ1,PARTICIPACIONQ2,PARTICIPACIONQ3,PARTICIPACIONQ4,PARTICIPACIONQ5,PARTICIPACIONQ6,PARTICIPACIONQ7,PARTICIPACIONQ8,PARTICIPACIONQ9,PARTICIPACIONQ10)
dataframe.SNames<- data.frame(StockSymbol=c(vector.Ssymbol),ETF=c(vector.etf),PARTICIPACION=c(vector.participacion))

write.csv(dataframe.SNames, file="ETFs.csv", row.names=TRUE)
